# Generated by Django 2.2 on 2022-06-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FB_App', '0002_auto_20220622_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_uploader', to='FB_App.User'),
        ),
    ]
